travis:
  secure:
    BINSTAR_TOKEN: P5jACYXa6nd30BXGKx4juRcokjzwiLcgg0og/3vs4dDsXDCckqFYx6QqOBK1gkN5gf/WIU6eaSgoICgX/Yj6GJ/ezjomh8QVsnEtEloXG4JVTUuYAny6JCTMSBX5jgyta6smv5cS/+cvSPe+617DV8j0u8ii03fKKMLTX2+CbyokV4HmsTVTpmvCeCrjvTJMnRWUHi2cvFkwkwjIYL2mQWpfyjkETdZpmwE0WTQGYZsGC2sRKCTmk3QyEGhHNc2K1SFJG5U9Nvn7iKZpgazw95UBvtiKxOEuP3M0Dnn6c0qXrMI40wbH3EGpeSkD9PPxNtVMl0EFPfPlDJjuQVYYeSdSSofbFbX6QfQrjScyxmjajJY30fh2Dd6bkhhiNYIiw4EHmPMEUP2GmqxMo7SEX1iOefCxcruAXnZe8vkB+FfmuLTuirvxMEE74Zj3ns0gVUxdGbh57wobyh0DhDjOisYxvbBGs/CVCVCna03EnUpPRdRFxTyFLq/z749cfQ1GKtMEbNBqGKFDfNu0K+Hf3JtpYdpDhgZIVwQcel6+MTRK8Lqaqn3Q3WbqpIO56PSd8+DZj/uvR4n1JprU4BdBCjSKyqSk7cVGr7KJtDj+7QqF/qJnaapAEuJOlYgnjgynH7/FaWnTgSYtCleOdd/cSIAi8wMjHr8xv8bp1uPwzZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
