travis:
  secure:
    BINSTAR_TOKEN: PpXbPspzM5yXRpDY3cXwglNSNSWd2crD5iCzIoC4gG8SF8jgsb3M9v7lnLOYhiep3WpMkNAjWQ59gxzZFEh+d3eKAHoYi6BBuXWFKMvfpCLEvEMO7Xmsm5uzwGnIw+se3+Bd/S/fGDU1BFKtuyqf0MR3g6uSF1Kzxy2vdDgerMvc1ZCm3+y2rnAtDv6d2ZPUHZT7JsyexarHduNBmYq/iPxchuUkgNIZOfttfiWKfUdbCAfF3su8whwmg73Jk72bWe+N6jMYg1MVYWoJxP+4DiuJ/T5Vtb0s7UO0gpH7dja7cAUzYqL5U7XYiQLz3KpGBh66DXliVXxT2F6JqtMtY1lY2R1z7EfgzeiJn+5nn4Wpxu6o3BerML/DoiJkc1Y+Iy+PAMYOPrWZbe4mOjOU8Ma6YIQ4b6nLzm1g4YO+3gmZIBhUreE+/OvtWl42gxrGrHFZowLPO1r4nSi+nNh0U3lZaqHs5zebV8n9RokjgcXyPCOURrriIePH68erO2J1rf3NlacNg8CGaXx7PFWM3wz+IQS4C/GSPu6fSxF2In/0UMgI6Oc2qNj9YTJYnKUj8kE8hAPGzMX8AcuGdK8C5XT/Ib4stus0/P1cDujMKmHI8ZGeciB06kDn/siCQIxQzbiQ0O+bOfyxm2WuPI+ZqZkmXuySTo1cXUle+kiZxnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
