travis:
  secure:
    BINSTAR_TOKEN: kxkihk2gLxoOoJfZ7aXmUgiyRJ39nSyweSegPfo9grlpkmUOjS5xWnu2ooCRO5WtbwLbG1nPZyn7dIB7k1p94AW9AI6cYotLhe/oMXxSwvymS9WKXUjHVBZ4j+DDxaH1RMRFA0fH8NteYVx/fPEpqEAmimdWRPaIRgplXfmRXrRr8T7SQ96w7ex11KsWBfLTjcl6ANR1+nJ0uPblfTErPY/W3w6nIS/xihurIalxSZ9fHbjURTL8UrdR7mgtt+6M6PWtU5l4RhfvDgz937N3f6CL2zHtkcYGCYFPIBMJkGw8ySh6wBBrWJyy6atynFsqXmKY2fM0YWnb5puTXlmDpCNzIDzBCOpLr839hW02qRjD1PqfDx/933gJszW1jIRYestMlTAH8RmT9HIy7+cybbBJDTAoO0IeV8VeK8C0KfI3OC3rtyLToNV9yQK7yO9e2YqKyOkr83ZVfbRIYN4QTDAH/Ih4aWK0a/2B4nfK8gl3/0j2MnuN1zN+2pAQl3CLk/LDAkk9GYpfAeq+k0nMzURbPlTWDj7ELRPaZXXHxjPVSu9ArT4C5zrBpHm7rrHs5W2YLqqTOfoLtP3rgsstjXoqdhq7//cp8iM+2J+jtlbzW5sw9brws17JMQu23oKXWsU0uxEyFrJXSQRVps0GQ5n9b05t2wn5eXnYolZ/QCA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
